name: Build and Push Image

on:
  push:
    branches: [ "bootc" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate lowercase image name
        run: |
          echo "LOWERCASE_REPOSITORY=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
      
      - name: Log into GHCR with Podman
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image with Podman
        run: |
          podman build -f ./Containerfile -t ghcr.io/${{ env.LOWERCASE_REPOSITORY }}:latest .
      
      - name: Push image with Podman
        run: |
          podman push ghcr.io/${{ env.LOWERCASE_REPOSITORY }}:latest