name: Build ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate lowercase image name
        run: |
          echo "LOWERCASE_REPOSITORY=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}

      - name: Build ISO
        id: build-iso
        uses: osbuild/bootc-image-builder-action@v1
        with:
          config-file: ./iso-config.toml
          image: ghcr.io/${{ env.LOWERCASE_REPOSITORY }}:latest
          types: |
            iso
      
      - name: Rename ISO
        run: |
          mv "${{ steps.build-iso.outputs.output-directory }}/iso/boot.iso" ./image.iso

      - name: Upload ISO
        uses: actions/upload-artifact@v7
        with:
          path: image.iso
          archive: false
          retention-days: 3