name: Deploy AION

on:
  workflow_dispatch:

env:
  IMAGE_NAME: aion
  IMAGE_REGISTRY: ghcr.io/marmocc

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull latest image
        run: |
          sudo podman pull ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Build ISO from image
        run: |
          mkdir -p output
          sudo podman run --rm --privileged \
            -v ./output:/output \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type iso \
            --ks kickstart.ks \
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: aion
          path: output/*.iso